# Welcome to Jekyll!
#

# Site settings
title: Kshiti & Suhas
description: |
  We're getting married! <br> <br> <br>
  Together with our families,<br>
  we joyfully invite you<br>
  to our wedding celebrations.<br> <br>

  <mark>Wedding:</mark> 16 - 17 March 2023 (Anand)

  <mark>Reception:</mark> 25 March 2023 (Mysuru)

owner: Suhas and Kshiti # or company name
first_published: 2022-2023 # if migrating another site, the year of your first publish
email: vijayakumar.suhas@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
